# Generated by Django 4.0.4 on 2022-12-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='sockets',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сокет'),
        ),
    ]
