# Generated by Django 4.0.1 on 2023-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/img/default.jpg', upload_to='profile_images', verbose_name='Изображение'),
        ),
    ]
