# Generated by Django 4.0.1 on 2022-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(upload_to='photos/categories'),
        ),
    ]
