# Generated by Django 4.0.1 on 2022-12-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0002_alter_categories_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('cost', models.IntegerField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyShop.categories')),
            ],
            options={
                'ordering': ['-cost', 'name'],
            },
        ),
    ]
