# Generated by Django 4.0.1 on 2022-12-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='cat',
        ),
    ]
