# Generated by Django 4.0.4 on 2023-01-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0003_alter_motherboard_form_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(blank=True, db_column='Форм-фактор', max_length=100, verbose_name='Форм-фактор'),
        ),
    ]
