# Generated by Django 4.0.4 on 2023-01-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0006_alter_motherboard_chipsets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MyShop.product')),
                ('model_card', models.CharField(blank=True, help_text='Модель', max_length=100, verbose_name='Модель')),
                ('power', models.CharField(blank=True, help_text='Живлення', max_length=100, verbose_name='Додаткове живлення')),
                ('memory', models.CharField(blank=True, help_text="Обсяг пам'яті", max_length=100, verbose_name="Обсяг пам'яті")),
                ('type_memory', models.CharField(blank=True, help_text="Тип пам'яті", max_length=100, verbose_name="Тип пам'яті")),
                ('memory_frequency', models.CharField(blank=True, help_text="Частота пам'яті", max_length=100, verbose_name="Частота пам'яті")),
                ('core_gpu', models.CharField(blank=True, help_text='Частота ядра GPU', max_length=100, verbose_name='Частота ядра')),
                ('mini_power', models.CharField(blank=True, default='-', help_text='Необхідна потужність БЖ', max_length=100, verbose_name='Необхідна потужність БЖ')),
                ('version_DirectX', models.CharField(blank=True, help_text='Версія DirectX', max_length=100, verbose_name='Версія DirectX')),
                ('type_cooling', models.CharField(blank=True, help_text='Тип охолодження', max_length=100, verbose_name='Тип охолодження')),
            ],
            options={
                'ordering': ['-cost', 'name'],
            },
            bases=('MyShop.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
