# Generated by Django 4.0.1 on 2023-03-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='call',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
