# Generated by Django 4.0.4 on 2023-01-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0006_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
