# Generated by Django 4.0.1 on 2023-03-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0007_userprofile_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='call',
        ),
    ]
