# Generated by Django 4.0.4 on 2023-01-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
