# Generated by Django 4.0.4 on 2023-02-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0010_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
