# Generated by Django 4.0.1 on 2023-03-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0012_comment_advantages_comment_disadvantages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-update', 'rating']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
