# Generated by Django 4.0.1 on 2023-03-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_price_orderitem_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='post_code',
            new_name='phone_number',
        ),
    ]
