# Generated by Django 4.0.1 on 2023-03-08 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
